### ISSUE TITLE
模擬案件#2 FeedPage実装まで

### ISSUE THREAD

**Issue by yasyun** [shinonome-inc/mobile_sakai#18]
・実装内容
　・Feed画面のデザイン実装
　・記事取得からTableViewへの表示までの仕組み実装
　・TableViewのセルをタップしてWebViewへ遷移→記事表示
　・TableViewCellを使ってセルの中身を実装
　・SearchBarで記事の検索機能実装

**Comment by yasyun** [comment]
・参考にしたサイト
https://qiita.com/Ajyarimochi/items/4f1597dc1934ac43d0e5
https://hajihaji-lemon.com/swift/uisearchbar/

・実装過程
　1. FeedPageUI作成
　2. 一旦記事一覧を通常通り表示してみる
　3. 画面遷移してWKWebViewで記事内容の表示実装
　4. TableViewCellの中身の実装
　5. SearchBar実装
　6. ページネーション実装
　7. 同じ記事の重複取得の修正や、検索機能のリファクタ実装

**Comment by yasyun** [comment]
・ページネーションのロジック
各indexPath内のcellが表示される直前にメソッドを呼び出し、「一度のリクエストで記事が20個以上取得されている」かつ「既に表示されたcellの数が、取得されている記事の数-10個の数と一致」という条件が満たされたときに、もう一度リクエストを行う。
結果、「取得してきた記事-10」個のcellが表示される直前で、リクエストを行うこととなる。

**Comment by yasyun** [comment]
・記事検索のロジックを変更したことに伴い、articleTitlesが必要なくなったので、リファクタのロジックも含め削除した。

**Comment by yasyun** [comment]
記事検索のロジック変更
・記事のタイトルを取得してきて、forEachを使って自力でテキストを見比べ、検索していた
　　↓
・filterとcontainsを使用し、SearchBarに入力した文字と記事のタイトルの中で、整合性のある記事だけを見つけられるように変更した

**Comment by yasyun** [comment]
記事のリファクタロジック

1. forEachでarticlesの中身を順番に取り出す
2. for in enumeratedで、forEachにより取り出されている記事と、全ての記事のタイトルを見比べる
3. overlapping(重複数)が2つ以上になったら、index(現在の配列インデックス)の記事を、articlesから削除する

**Comment by yasyun** [comment]
ユーザーアイコンの大きさ調整ロジック(もっと良い方法があれば改善)

・取得してきたユーザーアイコンの画像の大きさが、(width, height) = (300, 300)以上の非常に大きい画像の場合は、大きさを0.9倍ずつ縮めていって、画像の大きさが(50, 50)よりも小さくなったら、ImageViewに表示

・一方画像の大きさが(300, 300)以下で、(50, 50)よりも大きい画像の場合、画像の中央を(50, 50)で切り抜き、ImageViewに表示

**Comment by yasyun** [comment]
> ユーザーアイコンの大きさ調整ロジック(もっと良い方法があれば改善)
> 
> ・取得してきたユーザーアイコンの画像の大きさが、(width, height) = (300, 300)以上の非常に大きい画像の場合は、大きさを0.9倍ずつ縮めていって、画像の大きさが(50, 50)よりも小さくなったら、ImageViewに表示
> 
> ・一方画像の大きさが(300, 300)以下で、(50, 50)よりも大きい画像の場合、画像の中央を(50, 50)で切り抜き、ImageViewに表示

最初から画像を丸く切り取り、それをImageViewに当てはめるように変更。
結果、以前よりも綺麗にアイコンを表示することができるようになり、コードが簡潔になった。
- UIImage+Extension.swiftの中身を変更
- UIImageView+Extension.swift　⇒　EnhancedCircleImageView.swiftに名前を変更
- EnhancedCircleImageView.swiftの中身を変更

**Comment by mcz9mm** [comment]
Paginationで必要な考え方ね。
TableViewのCellが一番下までスクロールされたことを検知することがまず第一。
手法としては下記リンクになると思うので参考にすること。
https://stackoverflow.com/questions/39015228/detect-when-uitableview-has-scrolled-to-the-bottom

```
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if articles.count >= 20 && indexPath.row == ( articles.count - 10) {
            self.request()
        }
    }
```

あと、-10が多分スクロール中にスムーズに表示されるように調整してくれてると思うんだけど、
その意図がわからんのでコメントで意図を追記するとレビューするときに親切かな。
-10の数字の意味が伝わらないとそれはマジック変数になってしまいます。

> ・ページネーションのロジック
各indexPath内のcellが表示される直前にメソッドを呼び出し、「一度のリクエストで記事が20個以上取得されている」かつ「既に表示されたcellの数が、取得されている記事の数-10個の数と一致」という条件が満たされたときに、もう一度リクエストを行う。
結果、「取得してきた記事-10」個のcellが表示される直前で、リクエストを行うこととなる。

**Comment by yasyun** [comment]
ユーザーアイコン画像のキャッシュ化追加
iOSのデフォルトで内蔵されている、URLSessionを使用した。
使用した際に、TableViewを上下に動かしているとたまに、main thread以外でUIの更新を試みたことによるエラーでクラッシュしていたので、アイコンのImageViewに取得してきた画像を入れるところを、DispatchQueue.main.sync の中に入れ、確実にmain threadで処理できるようにしている。

**Comment by yasyun** [comment]
articlesのremove
検索時にremoveAllしていたがクラッシュの原因になっていた。
　↓
SearchBarに何かしら入力されている状態で検索が実行された時のみ、request()の中でremoveAllするように変更した。
