### ISSUE TITLE
模擬案件_#10_ErrorPage実装まで(QiitaOAuthPage, QiitaArticlePage, TagDetaiPage, FollowPage)

### ISSUE THREAD

**Issue by yasyun** [shinonome-inc/mobile_sakai#38]
- 実装内容
前回のErrorPage実装(issue:[#7](https://github.com/shinonome-inc/mobile_sakai/issues/35))と同様の内容を、QiitaOAuthPage, QiitaArticlePage, TagDetaiPage, FollowPageに実装

**Comment by yasyun** [comment]
- 実装過程
QiitaOAuthPage, QiitaArticlePage, TagDetaiPage, FollowPageにissue:[#7](https://github.com/shinonome-inc/mobile_sakai/issues/35)と同様の内容を実装

**Comment by yasyun** [comment]
QiitaOAuthPageとQiitaArticlePageはエラー発生までに若干時間がかかるため、errorViewが表示されるまでに若干ラグがある。

**Comment by yasyun** [comment]
QiitaOauthPageは認証ページを開く前と後のどちらでエラーが起きたかによって`func errorReload()`の挙動が変わる様に実装。
QiitaArticlePageは通常の実装だとすぐに再読み込みしてもすぐに正常に動作してしまい、その後素早く前の画面に戻るとその画面の`Alamofire`が動作せずまたerrorViewへ飛ばされてしまうため、条件としてFeedPageの情報が取得できたタイミングでerrorViewを閉じる様に実装した。

**Comment by yasyun** [comment]
TagDetailPageとFollowPageをNetwork link conditionarでもerrorViewが出てくる様に変更する。

**Comment by Kaito-a-bit** [comment]
`FeedPage`での スクロールのエラーがまだ確認されるので、どこかでブランチを切ってそちらの修正をお願いします。
shuさんに指摘していただいた[エラー](https://github.com/shinonome-inc/mobile_sakai/pull/36#issuecomment-991982810)です。

**Comment by ShuheiYoshidaJP** [comment]
https://github.com/shinonome-inc/mobile_sakai/issues/38#issuecomment-997718836
↓こちらでTimeoutを設定することにより改善できるような気がします。
https://qiita.com/shuuujin/items/9fbf3d1263e84a4aa47a
必要があれば別ブランチで実装してみてください。
しゅんやさんにお任せします。

本PRの機能としては満たしていたのでマージします。
